spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.52.88.176:3306/DB1_8?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8
    #url: jdbc:mysql://139.196.212.100:3306/oomall?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/oomall?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: user1_8
    password: ooad8

oomall:
  host: 139.196.212.100
  port: 6000
  user: 1940203832
  password: 123456
  adminuser: nan
  adminpassword: nan123
  norightuser: oomall
  norightpassword: oomall


logging:
  level:
    org.springframework: info