oomall:
  host: 47.100.32.48
  port: 8400
  user: 1940203832
  password: 123456
  adminuser: hi
  adminpassword: 123456
  norightuser: wowoto
  norightpassword: 123456

logging:
  level:
    org.springframework: info